apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ template "fullname" . }}
  template:
    metadata:
      labels:
        app: {{ template "fullname" . }}
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      containers:
      {{ include "gogs" . | indent 6 }}
      {{ include "memcached" . | indent 6 }}
      initContainers:
      {{ include "init" . | indent 6 }}
      {{ include "initPostgres" . | indent 6 }}
      volumes:
      - name: gogs-data
      {{- if .Values.persistence.enabled }}
        {{- if .Values.persistence.directGogsVolumeMount }}
{{ tpl .Values.persistence.directGogsVolumeMount . | indent 8 }}
        {{- else }}
        persistentVolumeClaim:
         claimName: {{ .Values.persistence.existingGogsClaim | default (include "fullname" .) }}
        {{- end }}
      {{- else }}
        emptyDir: {}
      {{- end }}
      {{ if (.Values.useInPodPostgres) }}
      - name: postgres-data
      {{- if .Values.persistence.enabled }}
        {{- if .Values.persistence.directPostgresVolumeMount }}
{{ tpl .Values.persistence.directPostgresVolumeMount . | indent 8 }}
        {{- else }}
        persistentVolumeClaim:
          claimName: {{ .Values.persistence.existingPostgresClaim | default (include "postgresql.fullname" .) }}
        {{- end }}
      {{- else }}
        emptyDir: {}
      {{- end }}
      {{- end }}
      - name: gogs-config
        configMap:
          name: {{ template "fullname" . }}

      {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
        - name: {{ .Values.imagePullSecrets }}
      {{- end }}
      {{- if .Values.affinity }}
      affinity:
{{ toYaml .Values.affinity | indent 8 }}
      {{- end }}
      {{- if .Values.tolerations }}
      tolerations:
{{ toYaml .Values.tolerations | indent 8 }}
      {{- end }}
